trigger:
  - main
  - develop
  - stage
  - release*
  - feature*

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  submodules: true
  persistCredentials : true

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: npm install --legacy-peer-deps
  displayName: 'NPM install with legacy peer dependencies'


- task: Npm@1
  displayName: NPM build
  inputs:
    command: 'custom'
    customCommand: 'run build'


- ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    - script: |
        cd dist/table-helper
        ls -la
      displayName: 'Change directory to dist/table-helper'

    - task: Npm@1
      displayName: NPM publish to NPM Registry
      inputs:
        command: 'publish'
        publishEndpoint: 'npm_cleverpine_dev_cicd'
